### PR TITLE
Update Package.swift and fix syntax for Swift 5

### PR DESCRIPTION
**Pull request by mattpolzin**
Pretty minor changes needed really to get it building and passing tests with Swift 5 and Swift 5 package manifest.

### CODE REVIEW

**Review by cfilipov — CHANGES_REQUESTED** [review]
Looks good. Thank you for the pull request. Any chance you can resolve the build failure on CI? https://travis-ci.org/cfilipov/TextTable/builds/568639062

**Comment by mattpolzin** [comment]
Oh, sure, that seems like something I ought to do. I’ll fix tonight.

**Comment by mattpolzin** [comment]
@cfilipov Good to go now. Great little library, by the way. I was surprised how hard it was to find textual table output libraries in Swift to begin with but on top of that your formatting options are awesome. I mean, I'm still smiling about the fact that you support LaTeX tables.

**Review by cfilipov — APPROVED** [review]
Thank you. I appreciate you took time to make a pull request. This reminds me I really should get back to refreshing this library. The new builder syntax in swift would make for a much better interface.

**Pull request merged**
